import { describe, expect, it } from 'vitest'
import { loadCuratedFoods } from '@/lib/curatedFoods'

describe('curated food table (generated by scripts/build-foods.mjs)', () => {
  it('has 150-300 entries with unique ids', async () => {
    const foods = await loadCuratedFoods()
    expect(foods.length).toBeGreaterThanOrEqual(150)
    expect(foods.length).toBeLessThanOrEqual(300)
    expect(new Set(foods.map((f) => f.id)).size).toBe(foods.length)
  })

  it('every entry cites a source id + URL and has sane numbers', async () => {
    for (const f of await loadCuratedFoods()) {
      expect(f.source.id, f.id).toBeTruthy()
      expect(f.source.url, f.id).toMatch(/^https:\/\//)
      expect(['AFCD', 'USDA SR Legacy', 'Open Food Facts (median)', 'Recipe of sourced records']).toContain(f.source.db)
      expect(f.per100g.kcal, f.id).toBeGreaterThanOrEqual(0)
      expect(f.per100g.kcal, f.id).toBeLessThanOrEqual(900)
      expect(f.serving.grams, f.id).toBeGreaterThan(0)
      expect(f.aliases.length, f.id).toBeGreaterThan(0)
    }
  })

  it('whey protein powder is 100-140 kcal per 30 g scoop', async () => {
    const whey = (await loadCuratedFoods()).find((f) => f.id === 'whey-protein-powder')!
    const per30 = whey.per100g.kcal * 0.3
    expect(per30).toBeGreaterThanOrEqual(100)
    expect(per30).toBeLessThanOrEqual(140)
  })

  it('only water-like drinks are 0 kcal', async () => {
    const zero = (await loadCuratedFoods()).filter((f) => f.per100g.kcal < 0.5).map((f) => f.id)
    expect(zero.sort()).toEqual(['cola-diet', 'tea', 'water']) // tea = black, no milk
  })
})
