// Food list for scripts/build-foods.mjs. This file holds NO nutrition numbers: only which real
// database record each food comes from, the words people use for it, and a default portion.
//
// src / ref forms:
//   'afcd:F000262'                       FSANZ Australian Food Composition Database, Release 3, by Public Food Key
//   'usda:173944'                        USDA FoodData Central SR Legacy, by fdc_id
//   { off: { category, terms } }         Open Food Facts search, median-kcal plausible product
//   { recipe: [['afcd:F000679', 120], ...] }  weighted mix of sourced records (grams are a portion
//                                         assumption, marked as such in the output)
// `ref` is an independent second source used by the live gate to check the table's numbers.
// `serve` = [grams, label]: a typical portion, an assumption (not a nutrition value).

export const FOODS = [
  // ── Supplements & protein ─────────────────────────────────────────────────────────────────
  { id: 'whey-protein-powder', name: 'Whey protein powder', cat: 'supplement', aliases: ['whey protein powder', 'whey protein', 'protein powder', 'whey', 'protein scoop'], src: 'afcd:F007493', ref: { off: { category: 'en:protein-powders', terms: 'whey' } }, serve: [30, '1 scoop'] },
  { id: 'protein-shake-water', name: 'Whey protein shake (with water)', cat: 'supplement', aliases: ['protein shake', 'whey shake', 'protein shake with water'], src: 'afcd:F009818', serve: [300, '1 shaker'] },
  { id: 'protein-bar', name: 'Protein bar', cat: 'supplement', aliases: ['protein bar', 'high protein bar'], src: { off: { category: 'en:protein-bars' } }, ref: 'afcd:F009802', serve: [60, '1 bar'] },
  { id: 'hemp-protein', name: 'Plant protein powder (hemp)', cat: 'supplement', aliases: ['hemp protein', 'plant protein powder', 'vegan protein powder'], src: 'afcd:F010642', serve: [30, '1 scoop'] },
  { id: 'muesli-bar', name: 'Muesli bar', cat: 'snack', aliases: ['muesli bar', 'granola bar', 'cereal bar'], src: 'afcd:F000333', serve: [35, '1 bar'] },
  { id: 'nut-bar', name: 'Nut bar', cat: 'snack', aliases: ['nut bar'], src: 'afcd:F009801', serve: [35, '1 bar'] },

  // ── Fruit ─────────────────────────────────────────────────────────────────────────────────
  { id: 'banana', name: 'Banana', cat: 'fruit', aliases: ['banana'], src: 'afcd:F000262', ref: 'usda:173944', serve: [120, '1 medium'] },
  { id: 'apple', name: 'Apple', cat: 'fruit', aliases: ['apple', 'red apple'], src: 'afcd:F000110', ref: 'usda:171688', serve: [150, '1 medium'] },
  { id: 'apple-green', name: 'Green apple', cat: 'fruit', aliases: ['green apple', 'granny smith'], src: 'afcd:F000098', serve: [150, '1 medium'] },
  { id: 'orange', name: 'Orange', cat: 'fruit', aliases: ['orange'], src: 'afcd:F006277', serve: [150, '1 medium'] },
  { id: 'mandarin', name: 'Mandarin', cat: 'fruit', aliases: ['mandarin', 'tangerine'], src: 'afcd:F005293', serve: [80, '1 mandarin'] },
  { id: 'pear', name: 'Pear', cat: 'fruit', aliases: ['pear'], src: 'afcd:F006601', serve: [160, '1 medium'] },
  { id: 'nashi', name: 'Nashi pear', cat: 'fruit', aliases: ['nashi', 'nashi pear', 'asian pear'], src: 'afcd:F006604', serve: [200, '1 nashi'] },
  { id: 'kiwifruit', name: 'Kiwifruit, green', cat: 'fruit', aliases: ['kiwifruit', 'kiwi fruit', 'kiwi', 'green kiwifruit'], src: 'afcd:F004816', serve: [75, '1 kiwifruit'] },
  { id: 'kiwifruit-gold', name: 'Kiwifruit, gold', cat: 'fruit', aliases: ['gold kiwifruit', 'gold kiwi', 'golden kiwi'], src: 'afcd:F004815', serve: [85, '1 kiwifruit'] },
  { id: 'grapes', name: 'Grapes, green', cat: 'fruit', aliases: ['grape', 'green grape'], src: 'afcd:F004260', serve: [100, '1 small bunch'] },
  { id: 'grapes-red', name: 'Grapes, red', cat: 'fruit', aliases: ['red grape'], src: 'afcd:F004259', serve: [100, '1 small bunch'] },
  { id: 'strawberries', name: 'Strawberries', cat: 'fruit', aliases: ['strawberry'], src: 'afcd:F008952', serve: [100, '1 punnet half'] },
  { id: 'blueberries', name: 'Blueberries', cat: 'fruit', aliases: ['blueberry'], src: 'afcd:F001290', serve: [75, '1/2 cup'] },
  { id: 'blueberries-frozen', name: 'Blueberries, frozen', cat: 'fruit', aliases: ['frozen blueberry', 'frozen berry'], src: 'afcd:F001289', serve: [75, '1/2 cup'] },
  { id: 'watermelon', name: 'Watermelon', cat: 'fruit', aliases: ['watermelon'], src: 'afcd:F005520', serve: [200, '1 wedge'] },
  { id: 'pineapple', name: 'Pineapple', cat: 'fruit', aliases: ['pineapple'], src: 'afcd:F006702', serve: [100, '2 rings'] },
  { id: 'mango', name: 'Mango', cat: 'fruit', aliases: ['mango'], src: 'afcd:F005299', serve: [150, '1 cheek pair'] },
  { id: 'peach', name: 'Peach', cat: 'fruit', aliases: ['peach'], src: 'afcd:F006573', serve: [150, '1 medium'] },
  { id: 'plum', name: 'Plum', cat: 'fruit', aliases: ['plum'], src: 'afcd:F006832', serve: [70, '1 plum'] },
  { id: 'avocado', name: 'Avocado', cat: 'fruit', aliases: ['avocado', 'avo'], src: 'afcd:F000162', serve: [75, '1/2 avocado'] },
  { id: 'feijoa', name: 'Feijoa', cat: 'fruit', aliases: ['feijoa'], src: 'afcd:F003818', serve: [50, '1 feijoa'] },
  { id: 'sultanas', name: 'Sultanas', cat: 'fruit', aliases: ['sultana', 'raisin'], src: 'afcd:F008983', serve: [30, '1 small box'] },
  { id: 'dates', name: 'Dates, dried', cat: 'fruit', aliases: ['date', 'dried date', 'medjool date'], src: 'afcd:F003496', serve: [30, '3 dates'] },

  // ── Vegetables & legumes ──────────────────────────────────────────────────────────────────
  { id: 'broccoli', name: 'Broccoli, boiled', cat: 'veg', aliases: ['broccoli', 'boiled broccoli'], src: 'afcd:F001900', serve: [90, '1 cup'] },
  { id: 'broccoli-raw', name: 'Broccoli, raw', cat: 'veg', aliases: ['raw broccoli'], src: 'afcd:F001905', serve: [90, '1 cup'] },
  { id: 'carrot', name: 'Carrot, raw', cat: 'veg', aliases: ['carrot', 'raw carrot'], src: 'afcd:F002276', serve: [80, '1 medium'] },
  { id: 'carrot-boiled', name: 'Carrot, boiled', cat: 'veg', aliases: ['boiled carrot', 'cooked carrot'], src: 'afcd:F002275', serve: [80, '1/2 cup'] },
  { id: 'potato-boiled', name: 'Potato, boiled', cat: 'veg', aliases: ['potato', 'boiled potato'], src: 'afcd:F007320', serve: [150, '1 medium'] },
  { id: 'potato-baked', name: 'Potato, baked', cat: 'veg', aliases: ['baked potato', 'roast potato', 'jacket potato'], src: 'afcd:F007314', serve: [150, '1 medium'] },
  { id: 'kumara', name: 'Kumara (orange), baked', cat: 'veg', aliases: ['kumara', 'sweet potato', 'orange kumara', 'roast kumara'], src: 'afcd:F009033', serve: [150, '1 medium piece'] },
  { id: 'kumara-boiled', name: 'Kumara (orange), boiled', cat: 'veg', aliases: ['boiled kumara', 'mashed kumara', 'boiled sweet potato'], src: 'afcd:F009034', serve: [150, '1 cup'] },
  { id: 'pumpkin', name: 'Pumpkin, baked', cat: 'veg', aliases: ['pumpkin', 'roast pumpkin'], src: 'afcd:F011005', serve: [120, '1 wedge'] },
  { id: 'butternut', name: 'Butternut, baked', cat: 'veg', aliases: ['butternut', 'butternut squash', 'butternut pumpkin'], src: 'afcd:F007533', serve: [120, '1 cup'] },
  { id: 'peas', name: 'Peas, frozen, boiled', cat: 'veg', aliases: ['pea', 'green pea', 'frozen pea'], src: 'afcd:F006538', serve: [80, '1/2 cup'] },
  { id: 'corn-cob', name: 'Corn on the cob, boiled', cat: 'veg', aliases: ['corn', 'corn on the cob', 'sweetcorn', 'corn cob'], src: 'afcd:F003200', serve: [100, '1 cob'] },
  { id: 'corn-canned', name: 'Corn kernels, canned', cat: 'veg', aliases: ['canned corn', 'corn kernel', 'whole kernel corn'], src: 'afcd:F003220', serve: [80, '1/2 cup'] },
  { id: 'spinach', name: 'Spinach, baby, raw', cat: 'veg', aliases: ['spinach', 'baby spinach'], src: 'afcd:F008749', serve: [30, '1 handful'] },
  { id: 'lettuce', name: 'Lettuce, iceberg', cat: 'veg', aliases: ['lettuce', 'iceberg lettuce', 'salad leaves'], src: 'afcd:F005192', serve: [30, '1 cup'] },
  { id: 'lettuce-cos', name: 'Lettuce, cos', cat: 'veg', aliases: ['cos lettuce', 'romaine'], src: 'afcd:F005191', serve: [30, '1 cup'] },
  { id: 'tomato', name: 'Tomato', cat: 'veg', aliases: ['tomato'], src: 'afcd:F009193', serve: [100, '1 medium'] },
  { id: 'tomato-cherry', name: 'Cherry tomatoes', cat: 'veg', aliases: ['cherry tomato'], src: 'afcd:F009190', serve: [80, '6 tomatoes'] },
  { id: 'cucumber', name: 'Cucumber, Lebanese', cat: 'veg', aliases: ['cucumber', 'lebanese cucumber'], src: 'afcd:F003321', serve: [80, '1/2 cucumber'] },
  { id: 'capsicum-red', name: 'Capsicum, red', cat: 'veg', aliases: ['capsicum', 'red capsicum', 'red pepper', 'bell pepper'], src: 'afcd:F002247', serve: [100, '1/2 capsicum'] },
  { id: 'capsicum-green', name: 'Capsicum, green', cat: 'veg', aliases: ['green capsicum', 'green pepper'], src: 'afcd:F002239', serve: [100, '1/2 capsicum'] },
  { id: 'onion', name: 'Onion, brown', cat: 'veg', aliases: ['onion', 'brown onion'], src: 'afcd:F006225', serve: [50, '1/2 onion'] },
  { id: 'onion-red', name: 'Onion, red', cat: 'veg', aliases: ['red onion'], src: 'afcd:F009800', serve: [50, '1/2 onion'] },
  { id: 'spring-onion', name: 'Spring onion', cat: 'veg', aliases: ['spring onion', 'scallion'], src: 'afcd:F006250', serve: [15, '1 stalk'] },
  { id: 'mushroom', name: 'Mushrooms, pan-fried', cat: 'veg', aliases: ['mushroom', 'fried mushroom'], src: 'afcd:F005945', serve: [70, '1/2 cup'] },
  { id: 'mushroom-raw', name: 'Mushrooms, raw', cat: 'veg', aliases: ['raw mushroom'], src: 'afcd:F005946', serve: [70, '1 cup'] },
  { id: 'cabbage', name: 'Cabbage, white, raw', cat: 'veg', aliases: ['cabbage', 'white cabbage'], src: 'afcd:F002015', serve: [70, '1 cup shredded'] },
  { id: 'cabbage-red', name: 'Cabbage, red, raw', cat: 'veg', aliases: ['red cabbage'], src: 'afcd:F002006', serve: [70, '1 cup shredded'] },
  { id: 'cauliflower', name: 'Cauliflower, boiled', cat: 'veg', aliases: ['cauliflower'], src: 'afcd:F002377', serve: [100, '1 cup'] },
  { id: 'green-beans', name: 'Green beans, boiled', cat: 'veg', aliases: ['green bean', 'bean'], src: 'afcd:F000430', serve: [80, '1/2 cup'] },
  { id: 'zucchini', name: 'Zucchini', cat: 'veg', aliases: ['zucchini', 'courgette'], src: 'afcd:F009775', serve: [100, '1/2 zucchini'] },
  { id: 'silverbeet', name: 'Silverbeet, boiled', cat: 'veg', aliases: ['silverbeet', 'chard'], src: 'afcd:F008266', serve: [80, '1/2 cup'] },
  { id: 'beetroot', name: 'Beetroot, canned', cat: 'veg', aliases: ['beetroot', 'canned beetroot'], src: 'afcd:F001010', serve: [50, '2 slices'] },
  { id: 'baked-beans', name: 'Baked beans', cat: 'legume', aliases: ['baked bean'], src: 'afcd:F000243', serve: [200, '1/2 can'] },
  { id: 'chickpeas', name: 'Chickpeas, canned', cat: 'legume', aliases: ['chickpea'], src: 'afcd:F002880', serve: [100, '1/2 cup'] },
  { id: 'lentils', name: 'Lentils, boiled', cat: 'legume', aliases: ['lentil'], src: 'afcd:F005177', serve: [150, '3/4 cup'] },
  { id: 'kidney-beans', name: 'Kidney beans, canned', cat: 'legume', aliases: ['kidney bean', 'red kidney bean'], src: 'afcd:F000448', serve: [100, '1/2 cup'] },
  { id: 'tofu', name: 'Tofu, firm', cat: 'legume', aliases: ['tofu', 'bean curd'], src: 'afcd:F009176', serve: [100, '1 slab'] },
  { id: 'hummus', name: 'Hummus', cat: 'legume', aliases: ['hummus', 'hommus'], src: 'afcd:F003539', serve: [30, '2 tbsp'] },

  // ── Bread, grains & cereals ───────────────────────────────────────────────────────────────
  { id: 'bread-white', name: 'White bread', cat: 'grain', aliases: ['white bread', 'bread', 'sandwich bread'], src: 'afcd:F001463', serve: [32, '1 slice'] },
  { id: 'toast-white', name: 'White toast', cat: 'grain', aliases: ['toast', 'white toast'], src: 'afcd:F001541', ref: 'usda:174925', serve: [32, '1 slice'] },
  { id: 'bread-wholemeal', name: 'Wholemeal bread', cat: 'grain', aliases: ['wholemeal bread', 'whole wheat bread', 'brown bread'], src: 'afcd:F001553', serve: [35, '1 slice'] },
  { id: 'toast-wholemeal', name: 'Wholemeal toast', cat: 'grain', aliases: ['wholemeal toast', 'brown toast'], src: 'afcd:F001597', serve: [35, '1 slice'] },
  { id: 'bread-grain', name: 'Mixed grain bread', cat: 'grain', aliases: ['mixed grain bread', 'multigrain bread', 'grain bread', 'vogels', 'vogel'], src: 'afcd:F001621', serve: [40, '1 slice'] },
  { id: 'toast-grain', name: 'Mixed grain toast', cat: 'grain', aliases: ['multigrain toast', 'grain toast', 'vogels toast'], src: 'afcd:F001644', serve: [40, '1 slice'] },
  { id: 'bread-sourdough', name: 'Sourdough bread', cat: 'grain', aliases: ['sourdough', 'sourdough bread'], src: 'afcd:F001537', serve: [40, '1 slice'] },
  { id: 'toast-sourdough', name: 'Sourdough toast', cat: 'grain', aliases: ['sourdough toast', 'toasted sourdough'], src: 'afcd:F001538', ref: 'usda:174911', serve: [40, '1 slice'] },
  { id: 'bread-rye', name: 'Rye sourdough', cat: 'grain', aliases: ['rye bread', 'rye sourdough'], src: 'afcd:F001450', serve: [40, '1 slice'] },
  { id: 'bagel', name: 'Bagel, toasted', cat: 'grain', aliases: ['bagel'], src: 'afcd:F000234', serve: [90, '1 bagel'] },
  { id: 'english-muffin', name: 'English muffin, toasted', cat: 'grain', aliases: ['english muffin'], src: 'afcd:F005898', serve: [65, '1 muffin'] },
  { id: 'crumpet', name: 'Crumpet, toasted', cat: 'grain', aliases: ['crumpet'], src: 'afcd:F003313', serve: [50, '1 crumpet'] },
  { id: 'wrap', name: 'Wrap, white', cat: 'grain', aliases: ['wrap', 'tortilla', 'white wrap'], src: 'afcd:F001415', serve: [60, '1 wrap'] },
  { id: 'pita', name: 'Pita bread', cat: 'grain', aliases: ['pita', 'pita bread', 'lebanese bread', 'pita pocket'], src: 'afcd:F001401', serve: [70, '1 pita'] },
  { id: 'bread-roll', name: 'Bread roll, white', cat: 'grain', aliases: ['bread roll', 'roll', 'bun'], src: 'afcd:F001353', serve: [60, '1 roll'] },
  { id: 'rice-white', name: 'White rice, cooked', cat: 'grain', aliases: ['white rice', 'rice', 'cooked rice', 'boiled rice', 'white rice cooked', 'steamed rice'], src: 'afcd:F007661', ref: 'usda:168878', serve: [180, '1 cup'] },
  { id: 'rice-brown', name: 'Brown rice, cooked', cat: 'grain', aliases: ['brown rice'], src: 'afcd:F007641', serve: [180, '1 cup'] },
  { id: 'pasta', name: 'Pasta, cooked', cat: 'grain', aliases: ['pasta', 'spaghetti', 'penne', 'fusilli'], src: 'afcd:F006456', serve: [180, '1 cup'] },
  { id: 'noodles-instant', name: 'Instant noodles, cooked', cat: 'grain', aliases: ['instant noodle', '2 minute noodle', 'two minute noodle', 'noodle', 'ramen'], src: 'afcd:F006053', serve: [200, '1 packet cooked'] },
  { id: 'noodles-rice', name: 'Rice noodles, cooked', cat: 'grain', aliases: ['rice noodle', 'rice stick', 'vermicelli'], src: 'afcd:F006038', serve: [150, '1 cup'] },
  { id: 'noodles-egg', name: 'Egg noodles, cooked', cat: 'grain', aliases: ['egg noodle'], src: 'afcd:F006044', serve: [150, '1 cup'] },
  { id: 'quinoa', name: 'Quinoa, cooked', cat: 'grain', aliases: ['quinoa'], src: 'afcd:F007596', serve: [150, '3/4 cup'] },
  { id: 'couscous', name: 'Couscous, cooked', cat: 'grain', aliases: ['couscous'], src: 'afcd:F003235', serve: [150, '3/4 cup'] },
  { id: 'oats', name: 'Rolled oats, dry', cat: 'cereal', aliases: ['oat', 'rolled oat', 'oatmeal'], src: 'afcd:F006143', serve: [40, '1/2 cup dry'] },
  { id: 'porridge-water', name: 'Porridge (made with water)', cat: 'cereal', aliases: ['porridge', 'porridge with water'], src: 'afcd:F007164', serve: [250, '1 bowl'] },
  { id: 'porridge-milk', name: 'Porridge (made with milk)', cat: 'cereal', aliases: ['porridge with milk', 'milk porridge'], src: 'afcd:F007156', serve: [250, '1 bowl'] },
  { id: 'muesli', name: 'Toasted muesli', cat: 'cereal', aliases: ['muesli', 'toasted muesli'], src: 'afcd:F005856', serve: [50, '1/2 cup'] },
  { id: 'muesli-natural', name: 'Natural muesli', cat: 'cereal', aliases: ['natural muesli', 'bircher muesli', 'untoasted muesli'], src: 'afcd:F005857', serve: [50, '1/2 cup'] },
  { id: 'granola', name: 'Granola', cat: 'cereal', aliases: ['granola'], src: 'afcd:F009807', serve: [50, '1/2 cup'] },
  { id: 'weet-bix', name: 'Weet-Bix', cat: 'cereal', aliases: ['weet bix', 'weetbix', 'wheat biscuit', 'weeties'], src: 'afcd:F001844', ref: { off: { terms: 'weet-bix' } }, serve: [30, '2 biscuits'] },
  { id: 'cornflakes', name: 'Cornflakes', cat: 'cereal', aliases: ['cornflake', 'corn flake'], src: 'afcd:F001701', serve: [30, '1 cup'] },
  { id: 'nutri-grain', name: 'Nutri-Grain', cat: 'cereal', aliases: ['nutri grain', 'nutrigrain'], src: 'afcd:F001767', serve: [30, '1 cup'] },
  { id: 'rice-bubbles', name: 'Rice Bubbles', cat: 'cereal', aliases: ['rice bubble', 'rice krispie'], src: 'afcd:F001803', serve: [30, '1 cup'] },
  { id: 'all-bran', name: 'All-Bran', cat: 'cereal', aliases: ['all bran'], src: 'afcd:F001829', serve: [45, '1/2 cup'] },
  { id: 'bran-flakes', name: 'Bran flakes', cat: 'cereal', aliases: ['bran flake'], src: 'afcd:F001818', serve: [30, '1 cup'] },
  { id: 'pancake', name: 'Pancake', cat: 'grain', aliases: ['pancake', 'pikelet', 'hotcake'], src: 'afcd:F006298', serve: [80, '1 large'] },
  { id: 'rice-cracker', name: 'Rice crackers', cat: 'snack', aliases: ['rice cracker'], src: 'afcd:F001152', serve: [20, '8 crackers'] },
  { id: 'cracker', name: 'Crackers (Salada style)', cat: 'snack', aliases: ['cracker', 'salada', 'cream cracker'], src: 'afcd:F001129', serve: [20, '3 crackers'] },
  { id: 'corn-thins', name: 'Corn thins', cat: 'snack', aliases: ['corn thin', 'corn cake'], src: 'afcd:F001115', serve: [12, '2 thins'] },
  { id: 'rice-cake', name: 'Rice cake', cat: 'snack', aliases: ['rice cake'], src: 'afcd:F001147', serve: [10, '1 cake'] },

  // ── Dairy & eggs ──────────────────────────────────────────────────────────────────────────
  { id: 'milk-whole', name: 'Milk, whole', cat: 'dairy', aliases: ['milk', 'whole milk', 'full fat milk', 'blue top milk', 'cow milk', 'standard milk'], src: 'afcd:F005634', ref: 'usda:171265', serve: [250, '1 glass (250 ml)'] },
  { id: 'milk-light', name: 'Milk, reduced fat', cat: 'dairy', aliases: ['light milk', 'lite milk', 'low fat milk', 'reduced fat milk', 'light blue milk'], src: 'afcd:F005614', serve: [250, '1 glass (250 ml)'] },
  { id: 'milk-trim', name: 'Milk, trim/skim', cat: 'dairy', aliases: ['trim milk', 'skim milk', 'skimmed milk', 'fat free milk', 'green top milk'], src: 'afcd:F005637', serve: [250, '1 glass (250 ml)'] },
  { id: 'oat-milk', name: 'Oat milk', cat: 'dairy-alt', aliases: ['oat milk', 'oat beverage', 'oat drink'], src: 'afcd:F006132', ref: { off: { category: 'en:oat-based-drinks' } }, serve: [250, '1 glass (250 ml)'] },
  { id: 'soy-milk', name: 'Soy milk', cat: 'dairy-alt', aliases: ['soy milk', 'soya milk'], src: 'afcd:F008720', serve: [250, '1 glass (250 ml)'] },
  { id: 'almond-milk', name: 'Almond milk', cat: 'dairy-alt', aliases: ['almond milk'], src: 'afcd:F009824', serve: [250, '1 glass (250 ml)'] },
  { id: 'cheddar', name: 'Cheddar cheese', cat: 'dairy', aliases: ['cheese', 'cheddar', 'cheddar cheese', 'tasty cheese', 'mild cheese'], src: 'afcd:F002414', serve: [20, '1 slice'] },
  { id: 'edam', name: 'Edam cheese', cat: 'dairy', aliases: ['edam'], src: 'afcd:F002448', serve: [20, '1 slice'] },
  { id: 'mozzarella', name: 'Mozzarella', cat: 'dairy', aliases: ['mozzarella'], src: 'afcd:F002472', serve: [30, '1/4 cup grated'] },
  { id: 'feta', name: 'Feta', cat: 'dairy', aliases: ['feta', 'fetta'], src: 'afcd:F002452', serve: [30, '1 cube'] },
  { id: 'cottage-cheese', name: 'Cottage cheese', cat: 'dairy', aliases: ['cottage cheese'], src: 'afcd:F002435', serve: [100, '1/2 cup'] },
  { id: 'cream-cheese', name: 'Cream cheese', cat: 'dairy', aliases: ['cream cheese', 'philadelphia'], src: 'afcd:F002444', serve: [20, '1 tbsp'] },
  { id: 'butter', name: 'Butter', cat: 'fat', aliases: ['butter'], src: 'afcd:F001973', serve: [10, '2 tsp'] },
  { id: 'margarine', name: 'Margarine spread', cat: 'fat', aliases: ['margarine', 'spread', 'flora'], src: 'afcd:F005309', serve: [10, '2 tsp'] },
  { id: 'cream', name: 'Cream, thickened', cat: 'dairy', aliases: ['cream', 'whipped cream', 'thickened cream'], src: 'afcd:F003270', serve: [30, '2 tbsp'] },
  { id: 'sour-cream', name: 'Sour cream', cat: 'dairy', aliases: ['sour cream'], src: 'afcd:F003269', serve: [30, '2 tbsp'] },
  { id: 'yoghurt-natural', name: 'Yoghurt, natural', cat: 'dairy', aliases: ['yoghurt', 'yogurt', 'natural yoghurt', 'plain yoghurt'], src: 'afcd:F009694', serve: [150, '1 pottle'] },
  { id: 'greek-yoghurt', name: 'Greek yoghurt, plain', cat: 'dairy', aliases: ['greek yoghurt', 'greek yogurt', 'greek style yoghurt'], src: 'usda:171304', ref: { off: { category: 'en:greek-style-yogurts', terms: 'plain' } }, serve: [150, '3/4 cup'] },
  { id: 'yoghurt-flavoured', name: 'Yoghurt, flavoured', cat: 'dairy', aliases: ['flavoured yoghurt', 'fruit yoghurt', 'strawberry yoghurt', 'vanilla yoghurt'], src: 'afcd:F009810', serve: [150, '1 pottle'] },
  { id: 'ice-cream', name: 'Ice cream, vanilla', cat: 'dessert', aliases: ['ice cream', 'vanilla ice cream'], src: 'afcd:F004508', serve: [70, '1 scoop'] },
  { id: 'custard', name: 'Custard', cat: 'dessert', aliases: ['custard'], src: 'afcd:F003442', serve: [100, '1/2 cup'] },
  { id: 'egg', name: 'Egg, boiled', cat: 'egg', aliases: ['egg', 'boiled egg', 'hard boiled egg'], src: 'afcd:F003721', ref: 'usda:173424', serve: [50, '1 large egg'] },
  { id: 'egg-fried', name: 'Egg, fried', cat: 'egg', aliases: ['fried egg'], src: 'afcd:F003718', serve: [50, '1 egg'] },
  { id: 'egg-poached', name: 'Egg, poached', cat: 'egg', aliases: ['poached egg'], src: 'afcd:F003725', serve: [50, '1 egg'] },
  { id: 'egg-scrambled', name: 'Scrambled eggs', cat: 'egg', aliases: ['scrambled egg'], src: 'afcd:F003732', serve: [120, '2 eggs'] },

  // ── Meat, fish & alternatives ─────────────────────────────────────────────────────────────
  { id: 'chicken-breast', name: 'Chicken breast, grilled', cat: 'meat', aliases: ['chicken breast', 'grilled chicken', 'chicken'], src: 'afcd:F002593', ref: 'usda:171477', serve: [150, '1 breast'] },
  { id: 'chicken-breast-baked', name: 'Chicken breast, baked', cat: 'meat', aliases: ['baked chicken breast', 'roast chicken breast', 'roast chicken'], src: 'afcd:F002590', serve: [150, '1 breast'] },
  { id: 'chicken-thigh', name: 'Chicken thigh, baked', cat: 'meat', aliases: ['chicken thigh'], src: 'afcd:F002804', serve: [120, '1 thigh'] },
  { id: 'chicken-drumstick', name: 'Chicken drumstick (with skin), baked', cat: 'meat', aliases: ['drumstick', 'chicken drumstick', 'chicken leg'], src: 'afcd:F002648', serve: [100, '1 drumstick'] },
  { id: 'beef-mince', name: 'Beef mince, cooked', cat: 'meat', aliases: ['mince', 'beef mince', 'ground beef', 'minced beef', 'savoury mince'], src: 'afcd:F000679', serve: [120, '1/2 cup'] },
  { id: 'beef-mince-lean', name: 'Lean beef mince, cooked', cat: 'meat', aliases: ['lean mince', 'lean beef mince'], src: 'afcd:F000667', serve: [120, '1/2 cup'] },
  { id: 'rump-steak', name: 'Rump steak, grilled', cat: 'meat', aliases: ['steak', 'rump steak', 'beef steak'], src: 'afcd:F000738', serve: [180, '1 steak'] },
  { id: 'scotch-fillet', name: 'Scotch fillet, grilled', cat: 'meat', aliases: ['scotch fillet', 'ribeye', 'rib eye'], src: 'afcd:F000846', serve: [180, '1 steak'] },
  { id: 'eye-fillet', name: 'Eye fillet, grilled', cat: 'meat', aliases: ['eye fillet', 'beef fillet', 'tenderloin'], src: 'afcd:F000835', serve: [150, '1 steak'] },
  { id: 'lamb-chop', name: 'Lamb loin chop, grilled', cat: 'meat', aliases: ['lamb chop', 'lamb loin chop', 'lamb'], src: 'afcd:F005043', serve: [100, '1 chop (meat)'] },
  { id: 'lamb-chop-lean', name: 'Lamb loin chop, lean, grilled', cat: 'meat', aliases: ['lean lamb chop', 'lean lamb'], src: 'afcd:F005026', serve: [100, '1 chop (meat)'] },
  { id: 'pork-chop', name: 'Pork chop, lean, BBQ', cat: 'meat', aliases: ['pork chop', 'pork'], src: 'afcd:F006921', serve: [150, '1 chop'] },
  { id: 'pork-belly', name: 'Pork belly, roasted', cat: 'meat', aliases: ['pork belly'], src: 'afcd:F006860', serve: [100, '1 piece'] },
  { id: 'pork-strips', name: 'Pork stir-fry strips', cat: 'meat', aliases: ['pork stir fry', 'pork strip'], src: 'afcd:F007127', serve: [120, '1 portion'] },
  { id: 'bacon', name: 'Bacon, middle rasher, cooked', cat: 'meat', aliases: ['bacon', 'bacon rasher', 'streaky bacon'], src: 'afcd:F000227', serve: [30, '1 rasher'] },
  { id: 'bacon-shortcut', name: 'Shortcut bacon, cooked', cat: 'meat', aliases: ['shortcut bacon'], src: 'afcd:F000231', serve: [30, '1 rasher'] },
  { id: 'ham', name: 'Ham, leg', cat: 'meat', aliases: ['ham', 'sliced ham'], src: 'afcd:F004299', serve: [30, '2 slices'] },
  { id: 'sausage-beef', name: 'Beef sausage, grilled', cat: 'meat', aliases: ['sausage', 'beef sausage', 'snarler', 'banger'], src: 'afcd:F008107', serve: [75, '1 sausage'] },
  { id: 'sausage-pork', name: 'Pork sausage, cooked', cat: 'meat', aliases: ['pork sausage'], src: 'afcd:F008143', serve: [75, '1 sausage'] },
  { id: 'sausage-chicken', name: 'Chicken sausage, cooked', cat: 'meat', aliases: ['chicken sausage'], src: 'afcd:F008119', serve: [75, '1 sausage'] },
  { id: 'sausage-vege', name: 'Vegetarian sausage, cooked', cat: 'meat-alt', aliases: ['vegetarian sausage', 'veggie sausage', 'vege sausage'], src: 'afcd:F008153', serve: [75, '1 sausage'] },
  { id: 'chorizo', name: 'Chorizo', cat: 'meat', aliases: ['chorizo'], src: 'afcd:F008126', serve: [40, '4 slices'] },
  { id: 'salmon', name: 'Salmon fillet, grilled', cat: 'fish', aliases: ['salmon', 'grilled salmon', 'salmon fillet'], src: 'afcd:F007826', serve: [150, '1 fillet'] },
  { id: 'salmon-smoked', name: 'Smoked salmon', cat: 'fish', aliases: ['smoked salmon'], src: 'afcd:F007864', serve: [50, '3 slices'] },
  { id: 'salmon-canned', name: 'Salmon, canned', cat: 'fish', aliases: ['canned salmon', 'tinned salmon'], src: 'afcd:F007853', serve: [90, '1 small can'] },
  { id: 'tuna-canned', name: 'Tuna, canned in water', cat: 'fish', aliases: ['tuna', 'canned tuna', 'tinned tuna', 'tuna in springwater'], src: 'afcd:F009300', serve: [95, '1 small can'] },
  { id: 'tuna-oil', name: 'Tuna, canned in oil', cat: 'fish', aliases: ['tuna in oil'], src: 'afcd:F009293', serve: [95, '1 small can'] },
  { id: 'fish-battered', name: 'Battered fish', cat: 'fish', aliases: ['battered fish', 'fried fish'], src: 'afcd:F003950', serve: [150, '1 piece'] },
  { id: 'fish-crumbed', name: 'Crumbed fish', cat: 'fish', aliases: ['crumbed fish', 'fish finger'], src: 'afcd:F003954', serve: [100, '1 fillet'] },
  { id: 'prawns', name: 'Prawns, cooked', cat: 'fish', aliases: ['prawn', 'shrimp', 'cooked prawn'], src: 'afcd:F007432', serve: [100, '8 prawns'] },

  // ── Nuts, spreads, oils & condiments ──────────────────────────────────────────────────────
  { id: 'peanut-butter', name: 'Peanut butter', cat: 'spread', aliases: ['peanut butter', 'pb'], src: 'afcd:F006577', ref: 'usda:172470', serve: [20, '1 tbsp'] },
  { id: 'almonds', name: 'Almonds', cat: 'nut', aliases: ['almond', 'raw almond'], src: 'afcd:F006081', serve: [30, '1 handful'] },
  { id: 'almonds-roasted', name: 'Almonds, roasted', cat: 'nut', aliases: ['roasted almond'], src: 'afcd:F006082', serve: [30, '1 handful'] },
  { id: 'cashews', name: 'Cashews, roasted, salted', cat: 'nut', aliases: ['cashew'], src: 'afcd:F006090', serve: [30, '1 handful'] },
  { id: 'peanuts', name: 'Peanuts, roasted, salted', cat: 'nut', aliases: ['peanut', 'salted peanut'], src: 'afcd:F006109', serve: [30, '1 handful'] },
  { id: 'walnuts', name: 'Walnuts', cat: 'nut', aliases: ['walnut'], src: 'afcd:F006116', serve: [30, '1 handful'] },
  { id: 'nutella', name: 'Hazelnut chocolate spread', cat: 'spread', aliases: ['nutella', 'hazelnut spread', 'chocolate spread'], src: 'afcd:F008777', serve: [20, '1 tbsp'] },
  { id: 'marmite', name: 'Marmite', cat: 'spread', aliases: ['marmite'], src: 'afcd:F008783', serve: [5, '1 tsp'] },
  { id: 'vegemite', name: 'Vegemite', cat: 'spread', aliases: ['vegemite'], src: 'afcd:F008785', serve: [5, '1 tsp'] },
  { id: 'honey', name: 'Honey', cat: 'spread', aliases: ['honey', 'manuka honey'], src: 'afcd:F004380', serve: [20, '1 tbsp'] },
  { id: 'jam', name: 'Jam, berry', cat: 'spread', aliases: ['jam', 'berry jam', 'strawberry jam', 'raspberry jam'], src: 'afcd:F004600', serve: [20, '1 tbsp'] },
  { id: 'olive-oil', name: 'Olive oil', cat: 'fat', aliases: ['olive oil', 'oil'], src: 'afcd:F006177', serve: [10, '2 tsp'] },
  { id: 'mayonnaise', name: 'Mayonnaise', cat: 'condiment', aliases: ['mayo', 'mayonnaise', 'aioli'], src: 'afcd:F005441', serve: [15, '1 tbsp'] },
  { id: 'tomato-sauce', name: 'Tomato sauce', cat: 'condiment', aliases: ['tomato sauce', 'ketchup'], src: 'afcd:F008083', serve: [15, '1 tbsp'] },
  { id: 'sugar', name: 'Sugar, white', cat: 'condiment', aliases: ['sugar', 'white sugar'], src: 'afcd:F008976', serve: [4, '1 tsp'] },
  { id: 'gravy', name: 'Gravy (from powder)', cat: 'condiment', aliases: ['gravy'], src: 'afcd:F004265', serve: [50, '1/4 cup'] },

  // ── Drinks ────────────────────────────────────────────────────────────────────────────────
  { id: 'flat-white', name: 'Flat white / latte (whole milk)', cat: 'drink', aliases: ['flat white', 'latte', 'cappuccino', 'coffee with milk', 'flat white coffee', 'coffee'], src: 'afcd:F009796', ref: { recipe: [['usda:171891', 30], ['usda:171265', 190]] }, serve: [220, '1 regular cup'] },
  { id: 'long-black', name: 'Long black', cat: 'drink', aliases: ['long black', 'black coffee', 'americano'], src: 'afcd:F003065', serve: [250, '1 cup'] },
  { id: 'espresso', name: 'Espresso', cat: 'drink', aliases: ['espresso', 'short black'], src: 'afcd:F003041', serve: [30, '1 shot'] },
  { id: 'instant-coffee', name: 'Instant coffee, black', cat: 'drink', aliases: ['instant coffee'], src: 'afcd:F003017', serve: [250, '1 mug'] },
  { id: 'tea', name: 'Tea, black, no milk', cat: 'drink', aliases: ['tea', 'black tea', 'cup of tea'], src: 'afcd:F009125', serve: [250, '1 mug'] },
  { id: 'green-tea', name: 'Green tea', cat: 'drink', aliases: ['green tea'], src: 'afcd:F009117', serve: [250, '1 mug'] },
  { id: 'water', name: 'Water', cat: 'drink', aliases: ['water', 'tap water', 'glass of water'], src: 'afcd:F009527', serve: [250, '1 glass'] },
  { id: 'orange-juice', name: 'Orange juice', cat: 'drink', aliases: ['orange juice', 'oj'], src: 'afcd:F004739', serve: [250, '1 glass'] },
  { id: 'apple-juice', name: 'Apple juice', cat: 'drink', aliases: ['apple juice'], src: 'afcd:F004663', serve: [250, '1 glass'] },
  { id: 'cola', name: 'Cola', cat: 'drink', aliases: ['coke', 'cola', 'coca cola', 'soft drink', 'fizzy drink', 'fizzy'], src: 'afcd:F008402', serve: [330, '1 can'] },
  { id: 'cola-diet', name: 'Diet cola', cat: 'drink', aliases: ['diet coke', 'coke zero', 'diet cola', 'zero sugar coke'], src: 'afcd:F008404', serve: [330, '1 can'] },
  { id: 'beer', name: 'Beer (4-4.9%)', cat: 'drink', aliases: ['beer', 'lager', 'pint'], src: 'afcd:F000994', serve: [330, '1 bottle'] },
  { id: 'wine-red', name: 'Red wine', cat: 'drink', aliases: ['red wine', 'wine'], src: 'afcd:F009571', serve: [150, '1 glass'] },
  { id: 'wine-white', name: 'White wine', cat: 'drink', aliases: ['white wine'], src: 'afcd:F009581', serve: [150, '1 glass'] },
  { id: 'sauvignon-blanc', name: 'Sauvignon blanc', cat: 'drink', aliases: ['sauvignon blanc', 'sav'], src: 'afcd:F009583', serve: [150, '1 glass'] },
  { id: 'milo', name: 'Milo with milk', cat: 'drink', aliases: ['milo', 'milo with milk', 'hot chocolate'], src: 'afcd:F001068', serve: [250, '1 mug'] },
  { id: 'red-bull', name: 'Energy drink (Red Bull)', cat: 'drink', aliases: ['red bull', 'energy drink'], src: 'afcd:F008421', serve: [250, '1 can'] },
  { id: 'v-energy', name: 'Energy drink (V)', cat: 'drink', aliases: ['v energy drink', 'v drink'], src: 'afcd:F008424', serve: [350, '1 can'] },
  { id: 'coconut-water', name: 'Coconut water', cat: 'drink', aliases: ['coconut water'], src: 'afcd:F009794', serve: [250, '1 glass'] },

  // ── Snacks, baking & treats ───────────────────────────────────────────────────────────────
  { id: 'potato-crisps', name: 'Potato chips (crisps), plain', cat: 'snack', aliases: ['chip', 'potato chip', 'crisp', 'potato crisp', 'ready salted chip'], src: 'afcd:F007193', serve: [45, '1 small bag'] },
  { id: 'corn-chips', name: 'Corn chips', cat: 'snack', aliases: ['corn chip', 'nacho chip', 'tortilla chip'], src: 'afcd:F003198', serve: [45, '1 small bag'] },
  { id: 'popcorn', name: 'Popcorn, butter flavoured', cat: 'snack', aliases: ['popcorn'], src: 'afcd:F006844', serve: [30, '1 bag'] },
  { id: 'chocolate-milk', name: 'Milk chocolate', cat: 'treat', aliases: ['chocolate', 'milk chocolate', 'choc', 'dairy milk'], src: 'afcd:F002929', serve: [40, '4 squares'] },
  { id: 'chocolate-dark', name: 'Dark chocolate', cat: 'treat', aliases: ['dark chocolate'], src: 'afcd:F002921', serve: [40, '4 squares'] },
  { id: 'biscuit-choc-chip', name: 'Chocolate chip biscuit', cat: 'treat', aliases: ['biscuit', 'cookie', 'chocolate chip cookie', 'choc chip biscuit'], src: 'afcd:F001170', serve: [20, '1 biscuit'] },
  { id: 'tim-tam', name: 'Chocolate-coated cream biscuit (Tim Tam style)', cat: 'treat', aliases: ['tim tam'], src: 'afcd:F001234', serve: [18, '1 biscuit'] },
  { id: 'anzac', name: 'Anzac biscuit', cat: 'treat', aliases: ['anzac biscuit', 'anzac'], src: 'afcd:F001164', serve: [20, '1 biscuit'] },
  { id: 'shortbread', name: 'Shortbread', cat: 'treat', aliases: ['shortbread'], src: 'afcd:F001244', serve: [20, '1 piece'] },
  { id: 'biscuit-plain', name: 'Plain sweet biscuit', cat: 'treat', aliases: ['plain biscuit', 'arrowroot biscuit', 'malt biscuit'], src: 'afcd:F001215', serve: [10, '1 biscuit'] },
  { id: 'gingernut', name: 'Ginger biscuit', cat: 'treat', aliases: ['ginger nut', 'gingernut', 'ginger biscuit'], src: 'afcd:F001195', serve: [15, '1 biscuit'] },
  { id: 'cake-chocolate', name: 'Chocolate cake, iced', cat: 'treat', aliases: ['chocolate cake', 'cake'], src: 'afcd:F002111', serve: [100, '1 slice'] },
  { id: 'cake-carrot', name: 'Carrot cake, iced', cat: 'treat', aliases: ['carrot cake'], src: 'afcd:F002100', serve: [100, '1 slice'] },
  { id: 'lamington', name: 'Lamington', cat: 'treat', aliases: ['lamington'], src: 'afcd:F002159', serve: [60, '1 lamington'] },
  { id: 'muffin-berry', name: 'Berry muffin', cat: 'treat', aliases: ['muffin', 'blueberry muffin', 'berry muffin'], src: 'afcd:F005877', serve: [120, '1 muffin'] },
  { id: 'muffin-choc', name: 'Chocolate chip muffin', cat: 'treat', aliases: ['chocolate muffin', 'chocolate chip muffin'], src: 'afcd:F005882', serve: [120, '1 muffin'] },
  { id: 'scone', name: 'Scone, plain', cat: 'treat', aliases: ['scone'], src: 'afcd:F008173', serve: [60, '1 scone'] },
  { id: 'doughnut', name: 'Jam doughnut', cat: 'treat', aliases: ['doughnut', 'donut', 'jam doughnut'], src: 'afcd:F003575', serve: [70, '1 doughnut'] },
  { id: 'doughnut-iced', name: 'Iced doughnut', cat: 'treat', aliases: ['iced donut', 'iced doughnut'], src: 'afcd:F003574', serve: [70, '1 doughnut'] },

  // ── Meals & takeaways ─────────────────────────────────────────────────────────────────────
  { id: 'meat-pie', name: 'Meat pie', cat: 'meal', aliases: ['pie', 'meat pie', 'mince pie', 'mince and cheese pie', 'steak pie', 'steak and cheese pie'], src: 'afcd:F006665', serve: [200, '1 pie'] },
  { id: 'chicken-pie', name: 'Chicken & vegetable pie', cat: 'meal', aliases: ['chicken pie'], src: 'afcd:F006656', serve: [200, '1 pie'] },
  { id: 'sausage-roll', name: 'Sausage roll', cat: 'meal', aliases: ['sausage roll'], src: 'afcd:F008098', serve: [130, '1 roll'] },
  { id: 'burger', name: 'Cheeseburger (fast food)', cat: 'meal', aliases: ['burger', 'hamburger', 'cheeseburger'], src: 'afcd:F004358', serve: [120, '1 burger'] },
  { id: 'burger-takeaway', name: 'Burger with salad (takeaway)', cat: 'meal', aliases: ['takeaway burger', 'burger with salad'], src: 'afcd:F004362', serve: [250, '1 burger'] },
  { id: 'hot-dog', name: 'Hot dog', cat: 'meal', aliases: ['hot dog'], src: 'afcd:F004389', serve: [120, '1 hot dog'] },
  { id: 'pizza-supreme', name: 'Pizza, supreme (takeaway)', cat: 'meal', aliases: ['pizza', 'supreme pizza'], src: 'afcd:F006800', serve: [200, '2 slices'] },
  { id: 'pizza-hawaiian', name: 'Pizza, ham & pineapple (takeaway)', cat: 'meal', aliases: ['hawaiian pizza', 'ham and pineapple pizza'], src: 'afcd:F006762', serve: [200, '2 slices'] },
  { id: 'pizza-cheese', name: 'Pizza, cheese & tomato', cat: 'meal', aliases: ['cheese pizza', 'margherita pizza'], src: 'afcd:F006725', serve: [200, '2 slices'] },
  { id: 'spring-roll', name: 'Spring roll', cat: 'meal', aliases: ['spring roll'], src: 'afcd:F008794', serve: [60, '1 roll'] },
  { id: 'lasagne', name: 'Beef lasagne, homemade', cat: 'meal', aliases: ['lasagne', 'lasagna'], src: 'afcd:F005146', serve: [300, '1 serve'] },
  { id: 'spag-bol', name: 'Spaghetti bolognese', cat: 'meal', aliases: ['spaghetti bolognese', 'spag bol', 'bolognese'], src: 'afcd:F006393', serve: [350, '1 bowl'] },
  { id: 'mac-cheese', name: 'Macaroni cheese', cat: 'meal', aliases: ['mac and cheese', 'macaroni cheese', 'mac n cheese'], src: 'afcd:F005259', serve: [250, '1 bowl'] },
  { id: 'hot-chips', name: 'Hot chips (takeaway)', cat: 'meal', aliases: ['hot chip', 'fries', 'french fry', 'takeaway chip', 'scoop of chips'], src: 'afcd:F007238', serve: [200, '1 scoop'] },
  { id: 'oven-chips', name: 'Oven chips', cat: 'meal', aliases: ['oven chip', 'oven fries', 'frozen chip'], src: 'afcd:F007242', serve: [150, '1 serve'] },

  // ── Kiwi combos (weighted mixes of sourced records; component grams are a portion assumption) ─
  { id: 'mince-on-toast', name: 'Mince on toast', cat: 'meal', aliases: ['mince on toast', 'mince toast'], src: { recipe: [['afcd:F000679', 120], ['afcd:F001541', 64]] }, ref: { recipe: [['usda:171799', 120], ['usda:174925', 64]] }, serve: [184, '1 plate (2 slices)'] },
  { id: 'fish-and-chips', name: 'Fish and chips', cat: 'meal', aliases: ['fish and chip', 'fish n chip', 'fush and chup'], src: { recipe: [['afcd:F003950', 150], ['afcd:F007238', 250]] }, serve: [400, '1 piece + 1 scoop'] },
  { id: 'sausage-sizzle', name: 'Sausage sizzle (sausage in bread)', cat: 'meal', aliases: ['sausage sizzle', 'sausage in bread', 'sausage on bread'], src: { recipe: [['afcd:F008107', 75], ['afcd:F001463', 32]] }, serve: [107, '1 sizzle'] },
  { id: 'pb-toast', name: 'Peanut butter on toast', cat: 'meal', aliases: ['peanut butter toast', 'peanut butter on toast'], src: { recipe: [['afcd:F001541', 32], ['afcd:F006577', 15]] }, serve: [47, '1 slice'] },
  { id: 'eggs-on-toast', name: 'Poached eggs on toast', cat: 'meal', aliases: ['egg on toast', 'eggs on toast', 'poached egg on toast'], src: { recipe: [['afcd:F003725', 100], ['afcd:F001541', 64]] }, serve: [164, '2 eggs, 2 slices'] },
  { id: 'beans-on-toast', name: 'Baked beans on toast', cat: 'meal', aliases: ['bean on toast', 'baked bean on toast'], src: { recipe: [['afcd:F000243', 200], ['afcd:F001541', 64]] }, serve: [264, '1/2 can, 2 slices'] },
  { id: 'cheese-on-toast', name: 'Cheese on toast', cat: 'meal', aliases: ['cheese on toast', 'cheese toastie'], src: { recipe: [['afcd:F002414', 30], ['afcd:F001541', 32]] }, serve: [62, '1 slice'] },
  { id: 'marmite-toast', name: 'Marmite toast with butter', cat: 'meal', aliases: ['marmite toast', 'marmite on toast'], src: { recipe: [['afcd:F001541', 32], ['afcd:F001973', 5], ['afcd:F008783', 4]] }, serve: [41, '1 slice'] },
  { id: 'buttered-toast', name: 'Buttered toast', cat: 'meal', aliases: ['buttered toast', 'toast with butter', 'butter toast'], src: { recipe: [['afcd:F001541', 32], ['afcd:F001973', 7]] }, serve: [39, '1 slice'] },
]
